### ISSUE TITLE
CardActor transformative =] convenience "By" moveBy() scaleBy() rotateBy()

### ISSUE THREAD

**Issue by kenlane33** [croquet/microverse#15]
Current...
translateTo(v:Vector3)
rotateTo(q:Quaternion)
scaleTo(s:Vector3)
positionTo(v:Vector3, q:Quaternion)

Some naming possibilities...
```
moveTo(v:Vector3)
rotateTo(q:Quaternion)
scaleTo(s:Vector3)
poseTo(v:Vector3, q:Quaternion)
```

The "By"s
```
moveBy(v:Vector3)
rotateBy(q:Quaternion)
scaleBy(s:Vector3)
poseBy(v:Vector3, q:Quaternion)
```

**Comment by yoshikiohshima** [comment]
I think "by" variations would be really good to have. One complication here is that we will want to have a way to specify variations with and without view side smoothing. So let us think about what are good rule.

**Comment by yoshikiohshima** [comment]
we have "by" variations (except for "pose"). We can close this issue, though it is good to have a variation of them with optional time parameter.
