### ISSUE TITLE
Tutorial links not working

### ISSUE THREAD

**Issue by codefrau** [croquet/microverse#21]
At the end of the main tutorial page https://croquet.io/docs/microverse/tutorial-Tutorial.html two tutorials are linked but both give a 404 error

**Comment by yoshikiohshima** [comment]
thanks. I look into a way to selectively generate the tutorial link when going through jsdoc.

**Comment by codefrau** [comment]
`tutorial1.md` and `tutorial2.md` also link to each other, giving a 404

**Comment by yoshikiohshima** [comment]
I think this issue is now fixed, and croquet.io/docs/microverse is updated (thanks!)
