### ISSUE TITLE
Firefox can only rotate objects on Mac.

### ISSUE THREAD

**Issue by IcarusCD** [croquet/microverse#24]
You can use ctrl-click to rotate an object while using Firefox on Mac, but that's it. You can't drag an object around.
You can do both on other combinations. For example, Win10/Firefox or Mac/Chrome. But not Mac/Firefox.

You can drag objects around on iPad/Firefox too, but that has the problem where mobile devices can only drag because that's the only option available.

**Comment by yoshikiohshima** [comment]
After quite a bit of investigation, I am concluding that we simply cannot use Ctrl-leftClick in our application when running on FireFox. So I think we will add Cmd-click as an equivalent gesture.

**Comment by yoshikiohshima** [comment]
Now Alt and Ctrl are treated as the same kind of modifier (intended to be true for all platforms).

**Comment by IcarusCD** [comment]
This problem isn't relevant, anymore.
