### ISSUE TITLE
Opera crashes on iPad

### ISSUE THREAD

**Issue by IcarusCD** [croquet/microverse#26]
As long as a portal is open, Opera repeatedly crashes on my iPad. I don't experience this on other devices. Regardless of Opera vs Opera mini. The app says the iPad's is vanilla Opera.

**Comment by yoshikiohshima** [comment]
Thank you for reporting. This may not be fixed in sometime, but not quite soon. If I'm not mistaken, Opera on iOS is using the same browser engine so it might be just the case that when they fix Safari to make Croquet work, Opera would just work.

**Comment by IcarusCD** [comment]
Replacing this with a new issue.
