### ISSUE TITLE
Can't load .glb in world js file. Needs to be .glb.zip

### ISSUE THREAD

**Issue by Croquetx** [croquet/microverse#56]
This does NOT work:
                dataLocation: "./assets/3D/ArtGallery1.glb",
but this does:
                dataLocation: "./assets/3D/ArtGallery1.glb.zip",
We should not require a file to be zipped to use it. I think this is an error.

**Comment by yoshikiohshima** [comment]
if you add 'modelType: "glb"', that should work at this moment. I had some reservation of just relying on the file name suffix but may be that is okay.
