### ISSUE TITLE
KTX2 Drag And Drop Fails to White

### ISSUE THREAD

**Issue by danielfearnot** [croquet/microverse#69]
Dragging and dropping a KTX2 (specifically ETC1S) texture compressed GLB into the test world causes all the textures to be white.  DevTools/Ctrl+Shift+i/Inspector Panel - > Network - > basis_transcoder.js and basis_transcoder.wasm both are red with "Request URL: https://croquet.io/lib/basis/basis_transcoder.js   Request Method: GET  Status Code: 404" and "Request URL: https://croquet.io/lib/basis/basis_transcoder.wasm   Request Method: GET   Status Code: 404" respectively

If I have the ktx2 glb loaded in default.js, the textures appear just fine. Oddly, drag and drop KTX2 works here https://causeverse.io/horse-events/ that is also running Microverse version 9e5d9a864611fc44571357e957a1dc3e58fc25fb commit or 0.7.5 . Please delete any placed objects immediately after testing in that space.

Test world: https://croquet.io/microverse/index.html?world=test&q=euc9ljrmvi#pw=a8uNQ5zkWjXK55IT1QVErw
Microverse Version: 6bba6457bafdfc6b70c24ac4c51e164c3060b89b commit or 0.7.5
Windows 11 Laptop CPU: i9-12900H
Opera GX: Your version isLVL 5 (core: 101.0.4843.85)
Test Object: [WaterBottleKTX2_ETC1S.glb](https://causeverse.io/waterbottlektx2_etc1s/)
![KTX2DragAndDropWhiteBottle](https://github.com/croquet/microverse/assets/13687382/9da254da-2ffc-440e-9c84-79ec40b004c2)

**Comment by yoshikiohshima** [comment]
The commit (4847cee) is supposed to fix it. Let me test it a bit more.

**Comment by yoshikiohshima** [comment]
The top level installation at croquet.io/microverse is updated. A new version of library will be rolled out later, as the current version works in that configuration.

**Comment by danielfearnot** [comment]
I see the textures in the old session ID, and when I dragged and dropped into a brand new [https://croquet.io/microverse/index.html?world=test](https://croquet.io/microverse/index.html?world=test&q=euc9ljrmvi#pw=a8uNQ5zkWjXK55IT1QVErw) space, the textures worked flawlessly. Closing the issue!
